nnoremap <C-x>0 :action CloseEditor<CR>
vnoremap <C-x>0 :action CloseEditor<CR>
nnoremap <C-x>1 :action UnsplitAll<CR>
vnoremap <C-x>1 :action UnsplitAll<CR>
nnoremap <C-x>2 :action SplitHorizontally<CR>
vnoremap <C-x>2 :action SplitHorizontally<CR>
nnoremap <C-x>3 :action SplitVertically<CR>
vnoremap <C-x>3 :action SplitVertically<CR>
nnoremap <C-x>o :action NextSplitter<CR>
vnoremap <C-x>o :action NextSplitter<CR>
